### ISSUE TITLE
关于path

### ISSUE THREAD

**Issue by gaoyuexit** [drinking/dsource#1]
./dsource [-ldc]  /path/to/pod    [/path/to/source]
/path/to/pod  ,   [/path/to/source]  分别是什么path, 可以说明一下么

**Comment by drinking** [comment]
@gaoyuexit 解决了吗？我有时间再优化下，现在好像是比较模糊

**Comment by gaoyuexit** [comment]
可以提供一些使用示例么?

**Comment by drinking** [comment]
@gaoyuexit  I update README and usage, have a look.
